etcd:
  endpoints: "127.0.0.1:2379"
  username: "root"
  password: "a12345"
  dialTimeout: 5
register:
  prefix: "/app/component/"
  key: "example"
  name: "cxgateway v2"
  addr: "http://127.0.0.1:9999"
  lease: 5