redis:
  url: '127.0.0.1'
  port: 6379
  password: 'a12345'
  db: 3
  expiration: 0
registeredPath: "/api/register"
remote:
  startInit: true
  name: test
  url: http://127.0.0.1
  destinations:
    0: 'http://127.0.0.1:8081'
    1: 'http://127.0.0.1:8081'
local:
  startInit: false
  name: test1
  url: http://127.0.0.1
  destinations:
    0: 'http://127.0.0.1:8081'
    1: 'http://127.0.0.1:8081'
