redis:
  url: '127.0.0.1'
  port: 6379
  password: 'a12345'
  db: 3
  expiration: 0
registeredPath: "/api/register"
auto-registered:
  - name: test
    url: http://127.0.0.1
    destinations:
      - http://127.0.0.1:8081
      - http://127.0.0.1:8081
  - name: test1
    url: http://127.0.0.1
    destinations:
      - http://127.0.0.1:8081
      - http://127.0.0.1:8081
